import type * as React from "react";
import {
  ArrowLeftIcon,
  ArrowRightIcon,
  BackpackIcon,
  BadgeIcon,
  BellIcon,
  BookmarkIcon,
  CalendarIcon,
  CameraIcon,
  CardStackIcon,
  ChatBubbleIcon,
  CheckCircledIcon,
  CheckIcon,
  CheckboxIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CircleBackslashIcon,
  CircleIcon,
  ClipboardIcon,
  ClockIcon,
  CodeIcon,
  ColorWheelIcon,
  CopyIcon,
  CounterClockwiseClockIcon,
  Cross1Icon,
  CrossCircledIcon,
  CubeIcon,
  DashboardIcon,
  DividerHorizontalIcon,
  DownloadIcon,
  EnvelopeClosedIcon,
  EnvelopeOpenIcon,
  ExclamationTriangleIcon,
  ExitIcon,
  ExternalLinkIcon,
  EyeNoneIcon,
  EyeOpenIcon,
  FaceIcon,
  FileIcon,
  FileTextIcon,
  FontBoldIcon,
  FontFamilyIcon,
  FontItalicIcon,
  GearIcon,
  GlobeIcon,
  GridIcon,
  Half2Icon,
  HamburgerMenuIcon,
  HeadingIcon,
  HeartIcon,
  HomeIcon,
  IdCardIcon,
  ImageIcon,
  InfoCircledIcon,
  InstagramLogoIcon,
  LaptopIcon,
  LightningBoltIcon,
  Link2Icon,
  LinkBreak2Icon,
  ListBulletIcon,
  LockClosedIcon,
  LockOpen1Icon,
  LoopIcon,
  MagicWandIcon,
  MagnifyingGlassIcon,
  MaskOnIcon,
  MinusCircledIcon,
  MinusIcon,
  MixerHorizontalIcon,
  MobileIcon,
  MoonIcon,
  OpacityIcon,
  PaperPlaneIcon,
  PauseIcon,
  Pencil1Icon,
  Pencil2Icon,
  PersonIcon,
  PieChartIcon,
  PinLeftIcon,
  PinRightIcon,
  PlayIcon,
  PlusCircledIcon,
  PlusIcon,
  QuestionMarkCircledIcon,
  QuestionMarkIcon,
  QuoteIcon,
  RadiobuttonIcon,
  ReaderIcon,
  ReloadIcon,
  ResetIcon,
  RocketIcon,
  RowsIcon,
  SewingPinIcon,
  SpeakerLoudIcon,
  SquareIcon,
  StarFilledIcon,
  StarIcon,
  SunIcon,
  SwitchIcon,
  TargetIcon,
  TextAlignCenterIcon,
  TextAlignLeftIcon,
  TextAlignRightIcon,
  TimerIcon,
  TokensIcon,
  TransparencyGridIcon,
  TrashIcon,
  UploadIcon,
  ViewGridIcon,
} from "@radix-ui/react-icons";

export type IconComponent = React.ComponentType<
  React.SVGAttributes<SVGElement>
>;

// Mappa nome-icona (stringa storica, ex legatura del font MySuperIcons) →
// componente SVG Radix Icons (@radix-ui/react-icons).
// Le chiavi sono quelle già salvate nel codice e a DB (DataType.icon,
// SocialLink.icon): non rinominarle, anche se non rispecchiano più il nome
// dell'icona Radix risolta.
// Il set Radix è molto più ridotto di quello precedente: le chiavi senza un
// equivalente ragionevole non sono in mappa e ricadono su FALLBACK_ICON.
export const ICON_MAP: Record<string, IconComponent> = {
  date_start: PinLeftIcon,
  date_end: PinRightIcon,
  quiz: QuestionMarkIcon,
  honour_star: StarFilledIcon,
  add: PlusIcon,
  remove: MinusIcon,
  add_a_photo: CameraIcon,
  add_photo_alternate: ImageIcon,
  arrow_back: ArrowLeftIcon,
  arrow_drop_down: ChevronDownIcon,
  arrow_forward: ArrowRightIcon,
  article: ReaderIcon,
  assignment: ClipboardIcon,
  auto_fix_high: MagicWandIcon,
  auto_stories: ReaderIcon,
  badge: BadgeIcon,
  block: CircleBackslashIcon,
  bookmark: BookmarkIcon,
  camera: CameraIcon,
  campaign: SpeakerLoudIcon,
  cancel: CrossCircledIcon,
  card_membership: IdCardIcon,
  category: GridIcon,
  check: CheckIcon,
  check_circle: CheckCircledIcon,
  chevron_left: ChevronLeftIcon,
  chevron_right: ChevronRightIcon,
  circle: CircleIcon,
  close: Cross1Icon,
  contrast: Half2Icon,
  dark_mode: MoonIcon,
  delete: TrashIcon,
  description: FileTextIcon,
  download: DownloadIcon,
  circle_check: CheckCircledIcon,
  draw: Pencil1Icon,
  list: ListBulletIcon,
  edit: Pencil2Icon,
  edit_note: Pencil2Icon,
  chat_done: ChatBubbleIcon,
  chat_favourite: ChatBubbleIcon,
  chat_feedback: ChatBubbleIcon,
  chat_cancel: ChatBubbleIcon,
  identity_card: IdCardIcon,
  dashboard: DashboardIcon,
  dashboard_add: DashboardIcon,
  email: EnvelopeClosedIcon,
  email_open: EnvelopeOpenIcon,
  emoji_emotions: FaceIcon,
  error: CrossCircledIcon,
  event: CalendarIcon,
  event_available: CalendarIcon,
  event_busy: CalendarIcon,
  event_check: CalendarIcon,
  expand_less: ChevronUpIcon,
  expand_more: ChevronDownIcon,
  favorite: HeartIcon,
  file_copy: CopyIcon,
  filter_list: MixerHorizontalIcon,
  font_download: FontFamilyIcon,
  groups: PersonIcon,
  undo: ResetIcon,
  help_center: QuestionMarkCircledIcon,
  history: CounterClockwiseClockIcon,
  home: HomeIcon,
  image: ImageIcon,
  important_devices: LaptopIcon,
  info: InfoCircledIcon,
  insert_drive_file: FileIcon,
  instagram: InstagramLogoIcon,
  inventory: CubeIcon,
  keyboard_arrow_down: ChevronDownIcon,
  keyboard_arrow_up: ChevronUpIcon,
  landscape: ImageIcon,
  language: GlobeIcon,
  light_mode: SunIcon,
  link: Link2Icon,
  location: SewingPinIcon,
  lock: LockClosedIcon,
  lock_open: LockOpen1Icon,
  logout: ExitIcon,
  xp: StarIcon,
  downtime: LightningBoltIcon,
  mail: EnvelopeClosedIcon,
  mail_outline: EnvelopeOpenIcon,
  menu: HamburgerMenuIcon,
  menu_book: ReaderIcon,
  notes_check: FileTextIcon,
  notes: FileTextIcon,
  bell: BellIcon,
  bell_ring: BellIcon,
  star: StarIcon,
  palette: ColorWheelIcon,
  pause_circle: PauseIcon,
  play_circle: PlayIcon,
  pause_circle_outline: PauseIcon,
  people: PersonIcon,
  person: PersonIcon,
  person_add: PersonIcon,
  photo_camera: CameraIcon,
  photo_library: ImageIcon,
  globe: GlobeIcon,
  radio_button_checked: RadiobuttonIcon,
  radio_button_unchecked: CircleIcon,
  refresh: ReloadIcon,
  repeat: LoopIcon,
  rocket_launch: RocketIcon,
  schedule: ClockIcon,
  search: MagnifyingGlassIcon,
  send: PaperPlaneIcon,
  settings: GearIcon,
  profile: IdCardIcon,
  stars: StarFilledIcon,
  chart_ring: PieChartIcon,
  texture: TransparencyGridIcon,
  theater_mask: MaskOnIcon,
  toggle_off: SwitchIcon,
  toggle_on: SwitchIcon,
  token: TokensIcon,
  travel_explore: GlobeIcon,
  tune: MixerHorizontalIcon,
  upcoming: TimerIcon,
  upload_file: UploadIcon,
  verified: CheckCircledIcon,
  visibility: EyeOpenIcon,
  visibility_off: EyeNoneIcon,
  warning: ExclamationTriangleIcon,
  water_drop: OpacityIcon,
  work: BackpackIcon,
  message_incoming: ChatBubbleIcon,
  message_multiple: ChatBubbleIcon,
  checkcheck: CheckIcon,
  list_view: RowsIcon,
  grid_view: ViewGridIcon,
  code: CodeIcon,
  remove_circle: MinusCircledIcon,
  add_circle: PlusCircledIcon,
  text_bold: FontBoldIcon,
  text_italic: FontItalicIcon,
  text_align_left: TextAlignLeftIcon,
  text_align_center: TextAlignCenterIcon,
  text_align_right: TextAlignRightIcon,
  heading: HeadingIcon,
  block_quote: QuoteIcon,
  horizontal_rule: DividerHorizontalIcon,
  unlink: LinkBreak2Icon,
  upload: UploadIcon,
  smartphone: MobileIcon,
  check_box: CheckboxIcon,
  check_box_outline_blank: SquareIcon,
  open_in_new: ExternalLinkIcon,
  cards: CardStackIcon,
  target: TargetIcon,
  mask: MaskOnIcon,
  eye: EyeOpenIcon,
};

// Icona neutra usata quando una chiave non è (più) presente in ICON_MAP
// (valori legacy o inattesi salvati a DB, o icone senza equivalente Radix).
export const FALLBACK_ICON: IconComponent = QuestionMarkCircledIcon;
